### ISSUE TITLE
command not found: nnictl

### ISSUE THREAD

**Issue by TeerathChandani** [imirzadeh/Teacher-Assistant-Knowledge-Distillation#6] opened 2019-07-29 06:56 UTC
I installed nni liberary. After that, when I try to install library, it shows me error. 

Please see the attachment

![error](https://user-images.githubusercontent.com/51108242/62027716-5dd9eb80-b219-11e9-95de-992fab927626.PNG)

**Comment by imirzadeh** [comment] 2019-07-29 12:27
From the error message, I think it didn't installed correctly or you need to restart your zsh session to be able to use it. Otherwise, you should have been able to use nnictl command.   
Maybe one of these is the cause?:
* There was an error during installation of nni and use missed the error message
* You don't have your virtualenv activated. For example, you installed nnictl in a virtualenv `v` and trying to use it somewhere else.
* you need to restart your zsh shell   
  
Anyway, the issue here is that you can't run nnictl. I suggest to check the nni repository for possible solutions.

Good Luck!

**Comment by TeerathKumar142** [comment] 2019-07-29 15:31
Thanks for your quick response..


I installed through: pip3 install nni 

then I run above command, and it showed error. 

I really do not know.. why issue is this.. Ok close this issue and we will talk on other issue. 

If library does not work.  Just tell me optimized value of your experiements. I asked in second issue. I am closing this issue. 

Thanks.

**Closed as completed** 2019-07-29 15:35 UTC
